# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('body', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('BR', 'breakfast'), ('LU', 'lunch'), ('DN', 'dinner')], default='BR', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(to='meals.Meal'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Restaurant'),
        ),
    ]
