COLLEGE_NAME = "snu"

# TODO: Add restaurant names to arrays

GRADUATE_DORM_RESTAURANTS = ['대학원기숙사식당']

SNUCO_RESTAURANTS = []

VET_RESTAURANTS = ['수의대식당']

RESTAURANTS = GRADUATE_DORM_RESTAURANTS + SNUCO_RESTAURANTS + VET_RESTAURANTS
