COLLEGE_NAME = "snu"

# TODO: Add restaurant names to arrays

GRADUATE_DORM_RESTAURANTS = []

SNUCO_RESTAURANTS = []

VET_RESTAURANTS = []

RESTAURANTS = GRADUATE_DORM_RESTAURANTS + SNUCO_RESTAURANTS + VET_RESTAURANTS
